output: false
pre-commit:
  commands:
    format:
      glob: "{**/*.yaml,**/*.yml,**/*.json}"
      run: |
        git diff --cached --name-only --diff-filter=ACM -- '*.yaml' '*.yml' | xargs -r yq eval -i '.'
        git diff --cached --name-only --diff-filter=ACM -- '*.json' | xargs -r yq eval -i -o=json '.'
commit-msg:
  commands:
    conventional:
      run: |
        grep -Eq '^(feat|fix|docs|style|ref|perf|test|ci|chore|rev)(\(.+\))?!?: .+' {1}
