name: buildx

on:
  workflow_call:
    outputs:
      image:
        value: ${{ jobs.build.outputs.image }}

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: [ self-hosted, linux ]

    outputs:
      image: ${{ steps.meta.outputs.image }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version
        id: version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="v1.0.${{ github.run_number }}"
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest \
                       -t ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }} \
                       . --quiet

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest > /dev/null 2>&1
          docker push ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }} > /dev/null 2>&1