name: buildx

on:
  workflow_call:
    outputs:
      image:
        value: ${{ jobs.buildx.outputs.image }}

jobs:
  buildx:
    runs-on: [ self-hosted, linux ]

    outputs:
      image: ${{ steps.meta_digest.outputs.image }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to GHCR
        run: |
          set -euo pipefail
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Define image
        id: meta_tag
        run: |
          set -euo pipefail
          IMAGE_NAME=$(yq '.image' ./config.yml)
          SHORT_SHA=${GITHUB_SHA::7}
          IMAGE=ghcr.io/${{ github.actor }}/${IMAGE_NAME}:${SHORT_SHA}
          echo "tag=$IMAGE" >> $GITHUB_OUTPUT
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Setup buildx
        run: |
          set -euo pipefail
          docker buildx create --name ci-builder --driver docker-container --use || docker buildx use ci-builder

      - name: Build and push
        id: build
        run: |
          set -euo pipefail
          IMAGE="${{ steps.meta_tag.outputs.tag }}"
          IMAGE_NAME="${{ steps.meta_tag.outputs.image_name }}"
          CACHE_IMAGE="ghcr.io/${{ github.actor }}/${IMAGE_NAME}:cache"

          docker buildx build \
            --platform linux/amd64 \
            --provenance=false \
            --sbom=false \
            --push \
            --cache-from=type=registry,ref=$CACHE_IMAGE \
            --cache-to=type=registry,ref=$CACHE_IMAGE,mode=max \
            -t $IMAGE .

      - name: Resolve digest
        id: meta_digest
        run: |
          set -euo pipefail

          IMAGE="${{ steps.meta_tag.outputs.tag }}"
          IMAGE_NAME="${{ steps.meta_tag.outputs.image_name }}"

          DIGEST=$(docker buildx imagetools inspect $IMAGE | grep Digest | head -n1 | awk '{print $2}')

          FINAL_IMAGE="ghcr.io/${{ github.actor }}/${IMAGE_NAME}@${DIGEST}"

          echo "image=$FINAL_IMAGE" >> $GITHUB_OUTPUT
