name: build

on:
  workflow_call:
    outputs:
      image:
        value: ${{ jobs.build.outputs.image }}

jobs:
  build:
    runs-on: [self-hosted, linux]

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    outputs:
      image: ${{ steps.meta.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Define image
        id: meta
        run: |
          IMAGE=${{ github.repository }}:local
          CACHE=ghcr.io/${{ github.repository }}:buildcache

          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "cache=$CACHE" >> $GITHUB_OUTPUT

      - name: Login GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Setup buildx
        run: |
          docker buildx create --use || true

      - name: Build with registry cache
        run: |
          docker buildx build \
            --load \
            --cache-from=type=registry,ref=${{ steps.meta.outputs.cache }} \
            --cache-to=type=registry,ref=${{ steps.meta.outputs.cache }},mode=max \
            -t ${{ steps.meta.outputs.image }} .
