name: build

on:
  workflow_call:
    outputs:
      image:
        value: ${{ jobs.build.outputs.image }}

jobs:
  build:
    runs-on: [self-hosted, linux]

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    outputs:
      image: ${{ steps.meta.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Define image
        id: meta
        run: |
          IMAGE=registry-runner-test:local
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          docker build -t ${{ steps.meta.outputs.image }} .
