name: login

on:
  workflow_call:

jobs:
  login:
    runs-on: [ self-hosted, linux ]
    steps:
      - name: Login GHCR and authenticate gh
        run: |
          set -euo pipefail

          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
