name: pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write

concurrency:
  group: image-push-${{ github.repository }}
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      runner: ubuntu-latest
