name: pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  release:
    needs: sign
    uses: guilhermelinosp/ci-templates/.github/workflows/release.yaml@latest
