name: pipeline

on:
  push:
    branches: [ main ]
    tags:
      - "v*"

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    uses: guilhermelinosp/ci-templates/.github/workflows/release.yaml@latest
