name: sbom

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      format:
        required: false
        default: "spdx-json"
        type: string

permissions:
  contents: read
  packages: read

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Install syft
        run: |
          wget -q "https://github.com/anchore/syft/releases/latest/download/syft_linux_amd64"
          chmod +x syft_linux_amd64
          sudo mv syft_linux_amd64 /usr/local/bin/syft

      - name: Generate SBOM
        run: |
          syft ${{ inputs.image }} \
            -o ${{ inputs.format }} \
            --file sbom.${{ inputs.format }}

      - name: Upload SBOM
        uses: actions/upload-artifact@v7
        with:
          name: sbom
          path: sbom.${{ inputs.format }}
