name: scan

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  scan:
    runs-on: [self-hosted, linux]

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Scan image (Trivy)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest \
            image --severity CRITICAL,HIGH --exit-code 1 ${{ inputs.image }}
