name: scan

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Trivy scan
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest \
            image --severity CRITICAL,HIGH --exit-code 1 ${{ inputs.image }}
