name: sign

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  sign:
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to GHCR
        run: |
          set -euo pipefail
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Define image
        id: meta_tag
        run: |
          set -euo pipefail
          IMAGE_NAME=$(yq '.image' ./config.yaml)
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Sign latest image
        run: |
          IMAGE_NAME="${{ steps.meta_tag.outputs.image_name }}"
          cosign sign --yes ghcr.io/${{ github.actor }}/${IMAGE_NAME}:latest

      - name: Sign version image
        run: |
          IMAGE_NAME="${{ steps.meta_tag.outputs.image_name }}"
          cosign sign --yes ghcr.io/${{ github.actor }}/${IMAGE_NAME}:${{ inputs.version }}
