name: sign

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  sign:
    runs-on: [ self-hosted, linux ]

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Validate input
        run: |
          set -euo pipefail

          IMAGE="${{ inputs.image }}"

          if [[ "$IMAGE" != *@sha256:* ]]; then
            echo "Image must be a digest (ghcr.io/...@sha256:...)" >&2
            exit 1
          fi

      - name: Sign image
        run: |
          set -euo pipefail
          COSIGN_EXPERIMENTAL=1 cosign sign --yes "${{ inputs.image }}"

      - name: Attest provenance
        run: |
          set -euo pipefail
          COSIGN_EXPERIMENTAL=1 cosign attest \
            --yes \
            --type slsaprovenance \
            "${{ inputs.image }}"
